# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170731_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='house',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
