# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, upload_to='users_image/', verbose_name='emblem'),
        ),
    ]
