# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='words',
            field=models.CharField(default='winter is comming', max_length=60),
            preserve_default=False,
        ),
    ]
