# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170730_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='places/', verbose_name='Castel img')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.House')),
            ],
        ),
    ]
