# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_castel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Castel img'),
        ),
        migrations.AlterField(
            model_name='castel',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.House'),
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='houses_emblems/', verbose_name='emblem'),
        ),
        migrations.AlterField(
            model_name='person',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.House'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='persons_image/', verbose_name='emblem'),
        ),
    ]
